### PR TITLE
Added firmware check

### PR DESCRIPTION
**Pull request by iprak**
Added header content check based on `tls_fwup_img_header_check` which checks the first 4 bytes for special value.

https://github.com/openshwprojects/OpenW600/blob/bd11804c91e06194f2a875ea62037fa1d5fae8ed/platform/common/fwup/wm_fwup.c#L71

### CODE REVIEW

**Comment by openshwprojects** [comment]
That's great, what about W800?

**Comment by iprak** [comment]
The magic value is the same so the same check should work for W800. I can make that change as well.

W600
`#define SIGNATURE_WORD      				0xa0ffff9f`


W800
`#define SIGNATURE_WORD      				(0xA0FFFF9FUL)`

**Comment by openshwprojects** [comment]
hmmm so giving W600 OTA to W800 would break the device?

**Comment by iprak** [comment]
I believe so.

The firmware headers are quite different. The header check in firmware update would prevent W800 firmware from being applied on W600.

* W800: https://github.com/openshwprojects/OpenW800/blob/cb8826eac07138fef502c05026374ed1601d30e6/include/platform/wm_fwup.h#L84
* W600: https://github.com/openshwprojects/OpenW600/blob/bd11804c91e06194f2a875ea62037fa1d5fae8ed/include/platform/wm_fwup.h#L70

**Comment by openshwprojects** [comment]
Ok, so now they are all safe to go? We can't now brick W600 and can't brick W800 by submitting wrong file?

What if we try to plug non-ota build to OTA form for W600?

**Comment by iprak** [comment]
Currently, the OTA implementation is only there for W600. W800 update will have to be done via the older app.

I attempted flashing W800 zipped (img) and W600 unzipped image (fls) and both failed in header check.

I have been unable to pass back the error message to client when the header check fails. I think what is happening is that the device closes the connection and browser reports `net::ERR_CONNECTION_RESET`. The OTA update for  BK7231 does not do any checks. I could not find any helpful sample in this regards but I will keep looking.

**Comment by openshwprojects** [comment]
Thank you, this is verry good. I will merge it now, but please look into w800 when you get one.

**Comment by iprak** [comment]
Can you take a look at https://github.com/openshwprojects/OpenBK7231T_App/pull/565 too? That is where the firmware check/actual functionality is.

**Pull request merged**
