### PR TITLE
Remove space from the end, because it prevents command from working

### PR DESCRIPTION
**Pull request by giedriuslt**

### CODE REVIEW

**Comment by openshwprojects** [comment]
Hey, can you elaborate? The C code should tolerate space at the end. If not, I need to check that with selftest on Windows.... hmmm I checked:
https://github.com/openshwprojects/OpenBK7231T_App/commit/f2dd2b4450522038e62a2fae67bed64fcbf33b3f
It seems to work, please provide more info on exactly what's breaking

**Comment by giedriuslt** [comment]
It does not for me:
image

**Comment by openshwprojects** [comment]
ah good point, so we are testing different endpoints, I am testing the Tasmota one, and you are testing the one introuced in the old times by btsimon (kept for comatpbility), let me see

**Comment by giedriuslt** [comment]
I would not say it's kept for compatibility, it's called from the UI "reset scripts"  button.

**Comment by openshwprojects** [comment]
Well, the story is that @btsimonh  introduced web app with OpenBeken custom endpoints and then I added Tasmota-compatibility layer, that's why we have two methods of calling commands...
Still, no problem, I'm on it, I will fix it in few moments:
image
Very good finding @giedriuslt , thank you for your continued support

**Comment by openshwprojects** [comment]
UPDATE: I think it indeed still executes the command, but it still returns the 400 code, because it tries to parse characters after ; as a command... fix coming soon

**Comment by openshwprojects** [comment]
backlog is culprit

**Comment by openshwprojects** [comment]
Done, here you can see what  I did:
https://github.com/openshwprojects/OpenBK7231T_App/commit/6526cda4c414b98051a11153d12fcb2335cf6313

**Comment by giedriuslt** [comment]
Good, but I still suggest to merge this so it's consistent

**Review by openshwprojects — APPROVED** [review]

**Comment by openshwprojects** [comment]
I think it is still important to merge it because of the older builds of OBK that are still around.... so, I'm merging

**Pull request merged**
