### PR TITLE
Changed the Css of the Webapp to match the native interface style

### PR DESCRIPTION
**Pull request by LuisThe0ne**
See last comment for changes.

### CODE REVIEW

**Comment by LuisThe0ne** [comment]
In the last commit I fixed some small issues and optimized the CSS a bit I think.
NOTE: I have never done anything with vue before, so I focused on the CSS. If I accidentely changed something I should not have changed, let me know!

**Comment by LuisThe0ne** [comment]
Resolved the merge conflicts.
Screenshots:
grafik
grafik
grafik
grafik

**Comment by LuisThe0ne** [comment]
To summarize:
I made a whole lot of changes! (I am not quite sure why Github thinks I have removed over 1000 lines of code and added over 1000 but ok.)
So my changes:
- I changed most of the Css of the Webapp to use the same styles as a the native UI interface to make the experience more fluent.
- I rewrote most of the HTML Layout of the deviceslList.html to make it look and feel better.
- I rewrote the whole CSS of the devicesList.html
- I removed the dependencys for Bootstrap.
- I removed the dependancy for jQuery, because everything worked fine without it.
- I moved some CSS of the Webapp into a seperate Stylesheet.
Here some Screenshots of the new UI:
NVIDIA_Share_N84WFPycfk
NVIDIA_Share_CO1m1m3i7J
You can preview the devicesList yourself [here](https://luisthe0ne.github.io/webapp/devicesList.html)
After I made the last commits everything should work, regarding paths.
Hope to hear some feedback soon.

**Comment by openshwprojects** [comment]
Not bad, altough my main concern is that now users will confuse Web Panel with HTTP Panel and will be unable to tell which part is Javascript and which is native. The positive side of having totally different Web App Style is that people can tell where are they.

Would you be able to support a style chooser with a style saved in cookie, and the default style will be that old white style and your "native style" would be selectable option?

My other concern would be that there are some unfinished things, like the text on buttons from OTA has bad contrast or there is an overlapping page on the devices list.

I must think about it.

Btw, if you know CSS and JS, there are some other things that may be needed. If you want, I can give you some ideas.

**Comment by LuisThe0ne** [comment]
I'm still learning but alway open for suggestions🙃

**Comment by LuisThe0ne** [comment]
In the latest commit Ia added mobile support to the devicesList, it works on many screen sizes, only on some the header overlaps with the content. I'm working on resolving the issue in the future.

**Comment by openshwprojects** [comment]
I will check it when I get some more time, but what about the "style changer" for the Web App? Would it be possible to by default keep old style, but allow users to choose new one from a some kind of drop down list and save result in Cookie?

**Comment by LuisThe0ne** [comment]
I think that would be a bit too complicated, I would recommend a different colour scheme.

**Comment by openshwprojects** [comment]
Wait, I will look into it, I remember I had such a mechanism on one of my websites in the past. I might help you with that.

**Comment by Gerigot** [comment]
you could use css variables at the root level and save some palette so that a user can choose what kind of colors he likes for the webapp page.
The problem with cookies or better localstorage is that are stored on the browser you are visiting the page with, so if you save those settings in your computer browser and after you open the page with your phone you'll have the old settings (default) but I think is not a big problem.
what can be done is to load from the localstorage the settings wanted or if not present set the default in some css variables and use those in the rest of the css

**Pull request closed without merging**
